# scheduler and worker on localhost
[node.localhost]
server_endpoint = { port = 4434 }
scheduler = { client_endpoint = { port = 4433 }, webui = true }
worker = { tags = [] }
storage = { path = "data" }
